import type { Photo } from '../types'

const base = import.meta.env.BASE_URL

/**
 * Bundled illustrated sample gallery. Used in development and whenever the
 * live Google Photos feed is unavailable, so the site never shows a hole.
 * The SVGs are generated by `scripts/generate-sample-photos.mjs`.
 */
export const samplePhotos: Photo[] = [
  { id: 'sample-01', src: `${base}sample/blaze-01.svg`, width: 800, height: 1000, alt: 'Illustration of Blaze sitting proudly in a warm sunset glow' },
  { id: 'sample-02', src: `${base}sample/blaze-02.svg`, width: 800, height: 800, alt: 'Illustration of a happy cat face with long whiskers' },
  { id: 'sample-03', src: `${base}sample/blaze-03.svg`, width: 800, height: 600, alt: 'Illustration of Blaze in classic loaf position' },
  { id: 'sample-04', src: `${base}sample/blaze-04.svg`, width: 800, height: 1066, alt: 'Illustration of Blaze batting a ball of yarn' },
  { id: 'sample-05', src: `${base}sample/blaze-05.svg`, width: 800, height: 800, alt: 'Illustration of a curious cat face under twinkling stars' },
  { id: 'sample-06', src: `${base}sample/blaze-06.svg`, width: 800, height: 640, alt: 'Illustration of Blaze gazing at a crescent moon' },
  { id: 'sample-07', src: `${base}sample/blaze-07.svg`, width: 800, height: 1000, alt: 'Illustration of Blaze sitting among floating paw prints' },
  { id: 'sample-08', src: `${base}sample/blaze-08.svg`, width: 800, height: 600, alt: 'Illustration of a sleepy cat loaf in pastel pink light' },
  { id: 'sample-09', src: `${base}sample/blaze-09.svg`, width: 800, height: 800, alt: 'Illustration of a winking cat face with a tiny heart' },
  { id: 'sample-10', src: `${base}sample/blaze-10.svg`, width: 800, height: 1066, alt: 'Illustration of Blaze chasing a trailing string of yarn' },
  { id: 'sample-11', src: `${base}sample/blaze-11.svg`, width: 800, height: 640, alt: 'Illustration of Blaze silhouetted against a starry night sky' },
  { id: 'sample-12', src: `${base}sample/blaze-12.svg`, width: 800, height: 1000, alt: 'Illustration of Blaze sitting tall like a tiny house panther' },
]
